'use client'

import { useState } from 'react'

const projects = ['KP Digital LMS', 'Donation Platform', 'Online Store', 'Pharmacy Management System', 'Library Management System', 'Student Dashboard', 'Purchase Requisition System', 'Quiz Platform']
const skills = { Backend: 'Laravel · PHP · REST APIs', Frontend: 'HTML5 · CSS3 · JavaScript · Bootstrap', Database: 'MySQL · SQLite', Tools: 'Git · GitHub · VS Code', Other: 'Responsive Design · MVC · AJAX' }
const services = ['Laravel Development', 'PHP Development', 'REST API Development', 'Responsive Web Design', 'Database Design', 'Full Stack Development']

export default function Page() {
  const [menu, setMenu] = useState(false)
  const [dark, setDark] = useState(true)
  const [sent, setSent] = useState(false)
  return <main className={dark ? 'site' : 'site light'}>
    <a className="skip" href="#about">Skip to content</a>
    <header className="nav"><a className="logo" href="#home"><span>OA</span><small>Softwares</small></a><button className="menu" onClick={() => setMenu(!menu)} aria-label="Toggle navigation">☰</button><nav className={menu ? 'links open' : 'links'}>{['Home','About','Education','Skills','Projects','Experience','Services','Contact'].map(x => <a key={x} href={`#${x.toLowerCase()}`} onClick={() => setMenu(false)}>{x}</a>)}</nav><button className="theme" onClick={() => setDark(!dark)} aria-label="Toggle theme">☼</button></header>
    <section className="hero" id="home"><div className="hero-copy"><span className="pill">SOFTWARE ENGINEERING &amp; SOLUTIONS</span><h1>Hi, I&apos;m <b>Imad Ud Din</b></h1><h3>I engineer as a <strong>Full Stack Developer</strong></h3><p>Passionate Software Engineer specializing in Laravel, PHP, JavaScript, REST APIs, and modern web application development. I build scalable, secure, and user-friendly applications for ambitious products and enterprise workflows.</p><div className="buttons"><a href="#projects" className="primary">▣ &nbsp; Explore My Work</a><a href="#contact" className="outline">⇩ &nbsp; Download Resume</a><a href="#contact" className="outline">✉ &nbsp; Contact Me</a></div><div className="checks"><span>✓ Clean Architecture</span><span>✓ REST API Expertise</span><span>✓ Laravel Full Stack</span></div></div><div className="hero-art"><div className="profile"><img src="https://github.com/ImadUdDin18.png?size=500" alt="Imad Ud Din"/><span>⌁ &nbsp; Laravel · Full Stack</span></div><div className="badge performance">⚡ <b>Performance</b><small>Optimized queries</small></div><div className="badge secure">◈ <b>Secure Auth</b><small>Roles &amp; policies</small></div><div className="code"><div><i/> <i/> <i/> <span>Engineer.php</span></div><pre>{`// High-performance Laravel stack\nnamespace App\\Core;\n\nclass SoftwareEngineer {\n  public function build() {\n    return [\n      'stack' => 'Laravel · PHP · MySQL',\n      'apis'  => 'REST · Auth · Secure',\n    ];\n  }\n}`}</pre></div></div></section>
    <section className="intro section" id="about"><div><span className="label">ABOUT ME</span><h2>Engineering Software That <b>Delivers Impact.</b></h2></div><div><p>I&apos;m a Software Engineer focused on building robust, scalable, and user-centered web applications. With a strong foundation in Laravel and PHP, I combine clean code, thoughtful architecture, and modern frontend practices to deliver solutions that make a difference.</p><a className="textlink" href="#projects">View My Work →</a></div></section>
    <section className="section education" id="education"><span className="label">EDUCATION</span><h2>Building a Strong <b>Foundation.</b></h2><article><span className="icon">▣</span><div><h3>Bachelor of Science in Software Engineering</h3><p>Software Engineering</p><small>Academic foundation in software development, algorithms, databases, and system design.</small></div><em>Education</em></article></section>
    <section className="section" id="skills"><span className="label">SKILLS</span><h2>Tools I Use to <b>Build.</b></h2><div className="skill-grid">{Object.entries(skills).map(([key,value]) => <article key={key}><h3>{key}</h3><p>{value}</p></article>)}</div></section>
    <section className="section projects" id="projects"><span className="label">SELECTED PROJECTS &amp; CASE STUDIES</span><h2>Work That Speaks for <b>Itself.</b></h2><div className="project-grid">{projects.map((p,i) => <article key={p}><div className="project-image">{String(i+1).padStart(2,'0')}</div><div className="project-body"><span className="tag">FULL STACK WEB APPLICATION</span><h3>{p}</h3><p>Scalable, secure, and user-friendly application built with modern engineering practices.</p><a href="https://github.com/ImadUdDin18" target="_blank" rel="noreferrer">GitHub ↗</a></div></article>)}</div></section>
    <section className="section experience" id="experience"><span className="label">EXPERIENCE</span><h2>Growing Through <b>Experience.</b></h2><article><span className="icon">⌘</span><div><h3>Software Engineer</h3><p>Full Stack Development</p><small>Developing reliable web applications and APIs with Laravel, PHP, JavaScript, and modern tooling.</small></div><em>Professional</em></article></section>
    <section className="section" id="services"><span className="label">CORE EXPERTISE BUILT FOR GROWTH</span><h2>How I Can <b>Help.</b></h2><div className="service-grid">{services.map((x,i)=><article key={x}><span>0{i+1}</span><h3>{x}</h3><p>Practical, maintainable solutions designed around your product goals.</p></article>)}</div></section>
    <section className="cta section" id="contact"><span className="label">LET&apos;S CONNECT</span><h2>Let&apos;s Build Something <b>Exceptional Together.</b></h2><p>Have a project in mind or want to collaborate? I&apos;d love to hear from you.</p><div className="contact-grid"><a href="mailto:imaduddin@example.com"><small>Email</small><b>imaduddin@example.com</b></a><a href="https://github.com/ImadUdDin18" target="_blank" rel="noreferrer"><small>GitHub</small><b>ImadUdDin18</b></a><div><small>Location</small><b>Pakistan</b></div></div><form onSubmit={e => {e.preventDefault(); setSent(true)}}><input required placeholder="Name"/><input required type="email" placeholder="Email"/><input required placeholder="Subject"/><textarea required placeholder="Message" rows={5}/><button className="primary">{sent ? 'Message Sent' : 'Send Message →'}</button></form></section>
    <footer><a className="logo" href="#home"><span>OA</span><small>Softwares</small></a><div><h4>Quick Links</h4><a href="#about">About</a><a href="#projects">Projects</a><a href="#experience">Experience</a></div><div><h4>Connect</h4><a href="https://github.com/ImadUdDin18">GitHub</a><a href="mailto:imaduddin@example.com">Email</a></div></footer>
  </main>
}
